# Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%matplotlib inline

# Read Dataset

In [6]:
from keras.preprocessing.image import ImageDataGenerator

## Image Augmentation

In [13]:
image_generator_train = ImageDataGenerator(rotation_range=30,
                                    width_shift_range=0.1,
                                    height_shift_range=0.1,
                                    rescale=1/255,
                                    shear_range=0.2,
                                    zoom_range=0.2,
                                    horizontal_flip=True,
                                    fill_mode='nearest')

image_generator_test = ImageDataGenerator(rescale=1/255)

In [15]:
train_img_gen = image_generator_train.flow_from_directory('dataset/training_set', 
                                                    target_size=(64, 64), 
                                                    batch_size=32, 
                                                    class_mode='binary')

Found 8000 images belonging to 2 classes.


In [17]:
test_img_gen = image_generator_test.flow_from_directory('dataset/test_set/',
                                                        target_size=(64, 64), 
                                                        batch_size=32, 
                                                        class_mode='binary')

Found 2000 images belonging to 2 classes.


In [18]:
train_img_gen.class_indices

{'cats': 0, 'dogs': 1}

In [20]:
train_img_gen.classes

array([0, 0, 0, ..., 1, 1, 1])

# Model Building

In [54]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, BatchNormalization

In [55]:
cnn = Sequential()

cnn.add(Conv2D(filters=32,
              kernel_size=3,
              activation='relu',
              input_shape=[64, 64, 3]))

cnn.add(MaxPool2D(pool_size=2, strides=2))

cnn.add(Conv2D(filters=32,
              kernel_size=3,
              activation='relu'))

cnn.add(MaxPool2D(pool_size=2, strides=3))

cnn.add(Flatten())

cnn.add(Dense(3200, activation='relu'))

cnn.add(BatchNormalization())

cnn.add(Dense(1600, activation='relu'))

cnn.add(BatchNormalization())

cnn.add(Dense(1600, activation='relu'))

cnn.add(Dense(1, activation='sigmoid'))

In [56]:
cnn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [57]:
cnn.fit(x=train_img_gen, validation_data=test_img_gen, epochs=25, steps_per_epoch=250, batch_size=32)

Epoch 1/25
250/250 [==============================] - 109s 436ms/step - loss: 1.0561 - accuracy: 0.5576 - val_loss: 0.6775 - val_accuracy: 0.5710
Epoch 2/25
250/250 [==============================] - 109s 435ms/step - loss: 0.6789 - accuracy: 0.6261 - val_loss: 0.6257 - val_accuracy: 0.6250
Epoch 3/25
250/250 [==============================] - 113s 451ms/step - loss: 0.6120 - accuracy: 0.6654 - val_loss: 0.7583 - val_accuracy: 0.6440
Epoch 4/25
250/250 [==============================] - 119s 477ms/step - loss: 0.5920 - accuracy: 0.6915 - val_loss: 0.5648 - val_accuracy: 0.7300
Epoch 5/25
250/250 [==============================] - 118s 471ms/step - loss: 0.5828 - accuracy: 0.6934 - val_loss: 0.5667 - val_accuracy: 0.7090
Epoch 6/25
250/250 [==============================] - 117s 469ms/step - loss: 0.5748 - accuracy: 0.7039 - val_loss: 0.5417 - val_accuracy: 0.7320
Epoch 7/25
250/250 [==============================] - 110s 441ms/step - loss: 0.5648 - accuracy: 0.7139 - val_loss: 0.5655 -

In [58]:
cnn.save('Dog-or-Cat-1.h5')

# Single Prediction

In [47]:
from keras.preprocessing import image

dog_img = image.img_to_array(image.load_img('dataset/single_prediction/cat_or_dog_1.jpg', target_size=(64, 64)))

dog_img = np.expand_dims(dog_img, 0)

dog_img = dog_img / 255

In [48]:
cnn.predict(dog_img)

array([[0.99923766]], dtype=float32)

In [49]:
cat_img = image.img_to_array(image.load_img('dataset/single_prediction/cat_or_dog_2.jpg', target_size=(64, 64)))

cat_img = np.expand_dims(dog_img, 0)

cat_img = dog_img / 255

In [50]:
cnn.predict(cat_img)

array([[0.04867071]], dtype=float32)